pipelines:
  default:
    - step:
        name: Commit work
        script:
          - echo "Thank you for feeding me with more code!"
    - step:
        caches:
          - gradle
        name: Build app
        image: androidsdk/android-30
        script:
          - bash ./gradlew clean assembleRelease -Pmaven_access=$MAVEN_ACCESS -Pmaven_secret=$MAVEN_SECRET -Pmaven_repo=$MAVEN_REPO
    - step:
        caches:
          - gradle
        name: Publish to Maven
        image: androidsdk/android-30
        trigger: manual
        deployment: production
        script:
          - bash ./gradlew :bedrock:publish -Pmaven_access=$MAVEN_ACCESS -Pmaven_secret=$MAVEN_SECRET -Pmaven_repo=$MAVEN_REPO
