pipelines:
  default:
    - step:
        name: Commit work
        script:
          - echo "Thank you for feeding me with more code!"
    - step:
        name: Publish to Maven
        image: java:8
        trigger: manual
        deployment: production
        script:
          - bash ./gradlew :bedrock:publish -Pmaven_access=$maven_access -Pmaven_secret=$maven_secret
